# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CardApplication' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CardApplication
	pod 'RxSwift','~> 4.0' 
  	pod 'RxCocoa','~> 4.0'
  	pod 'ImageSlideshow', '~> 1.9.0'
  	pod 'VerticalSteppedSlider'
  	pod 'MultiProgressView'
  	pod 'GTProgressBar'

end
